name: Manual Publish Vscode

on:
  workflow_dispatch:
    inputs:
      pre-release:
        description: "Pre release"
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write

jobs:
  publish-vscode:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Install vsce and ovsx
        run: npm install -g @vscode/vsce ovsx

      - name: Pack for Vscode
        run: npm run package:vsce

      - name: Publish to VS Code Marketplace
        if: ${{ !inputs.pre-release }}
        run: vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}

      - name: Publish to VS Code Marketplace (Pre-release)
        if: ${{ inputs.pre-release }}
        run: vsce publish --pre-release
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: seamless-agent-vsix
          path: seamless-agent-*.vsix

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v3
        id: attestation
        with:
          subject-path: "seamless-agent-*.vsix"

      - name: Add provenance to release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          body: |
            ---
            [Provenance attestations](${{ steps.attestation.outputs.attestation-url }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
